POST http://localhost:3001/products
Content-Type: application/json

{
    "barCode": "5449000000996",
    "userId": "user_2u94I2vSjP1M6OcnBmkbrmVReCb"
}

###

GET  http://localhost:3001/products/user_2u94I2vSjP1M6OcnBmkbrmVReCb
