POST http://localhost:3001/api/routes/users
Content-Type: application/json

{
    "barCode": "3017620422003",
    "userId": "user_2u94I2vSjP1M6OcnBmkbrmVReCb"
}

###

GET  http://localhost:3001/api/routes/users
