POST http://localhost:3001/products
Content-Type: application/json

{
    "barCode": "8024370017446",
    "userId": "user_2uSC1DkP75fkiMZ7j2PUP14dDxk"
}

###

GET  http://localhost:3001/products/user_2uSC1DkP75fkiMZ7j2PUP14dDxk

###
GET https://tidy-seagull-forcibly.ngrok-free.app/products/user_2uSC1DkP75fkiMZ7j2PUP14dDxk

###
PUT http://localhost:3001/products/67dab81512ec38464f62abf3/edit
Content-Type: application/json

{
    "userId": "user_2uSC1DkP75fkiMZ7j2PUP14dDxk",
    "expiryDate": "2024-03-31T00:00:00.000Z"
}

###

GET http://localhost:3001/recipes/user_2uSC1DkP75fkiMZ7j2PUP14dDxk

###

POST http://localhost:3001/products/delete
Content-Type: application/json

{
    "userId": "user_2uSC1DkP75fkiMZ7j2PUP14dDxk",
    "barcode": "8000090007448"
}